name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # Step 1: Run Unit Tests
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q

  # Step 2: Train Model and Quantize
  train-and-quantize:
    runs-on: ubuntu-latest
    needs: test-suite
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python src/train.py

      - name: Quantize model
        run: |
          python src/quantize.py

      - name: Verify model files
        run: |
          ls -l models/

  # Step 3: Build Docker Image and Run Container
  build-and-run-docker:
    runs-on: ubuntu-latest
    needs: train-and-quantize
    services:
      docker:
        image: docker:20.10.16
        options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub (optional, skip if no push)
        if: false  # Disabled. Enable if pushing to DockerHub.
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t mlops-housing .

      - name: Run Docker container
        run: |
          docker run --rm mlops-housing


