name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-suite:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/ --maxfail=1 --disable-warnings -q

  train-and-quantize:
    runs-on: ubuntu-latest
    needs: test-suite
    env:
      PYTHONPATH: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: python src/train.py

      - name: Quantize model
        run: python src/quantize.py

      - name: List models directory
        run: ls -l models/

      - name: Upload models directory
        uses: actions/upload-artifact@v4
        with:
          name: models
          path: models/

  build-and-run-docker:
    runs-on: ubuntu-latest
    needs: train-and-quantize
    env:
      PYTHONPATH: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download models artifact
        uses: actions/download-artifact@v4
        with:
          name: models
          path: models/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t mlops-housing .

      - name: Run Docker container
        run: docker run --rm mlops-housing

